lamp:
  nginx:
    ip: 127.0.0.1      # 正式环境需要将该ip设置成nginx对应的 公网ip
    port: 10000
  cache:
    type: REDIS
  redis:
    ip: 81.70.207.162
    port: 6379
    password: lamp_redis
    database: 0
  rabbitmq:
    enabled: false
    ip: 81.70.207.162
    port: 5672
    username: admin
    password: admin
  mysql:
    #    ip: 81.70.207.162 #81docker
    ip: rm-uf68h64hwg6p58k7dlo.mysql.rds.aliyuncs.com #阿里云
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: lamp_defaults
    #    username: root #81docker
    username: xiaonie #阿里云
    #    password: fYTTIHITbf1EaZdCeQaPYEJTVf4363AT #81docker
    password: Nfh50200 #阿里云
    url: jdbc:mysql://${lamp.mysql.ip}:${lamp.mysql.port}/${lamp.mysql.database}?characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true

tencentcloud:
  sms:
    secretId: AKIDkGVX7Tk8i25uSiH4f7KGxe5GAoCmrTO6
    secretKey: cx2PaZY5MXgdGd06wVmmfHOm37xYu0vb
    appId: 1400496989
    sign: JavaE开发
    templateId: 1232978