lamp:
  nginx:
    ip: 127.0.0.1      # 正式环境需要将该ip设置成nginx对应的 公网ip
    port: 9090
  cache:
    type: REDIS
  redis:
    ip: 81.70.207.162
    port: 6379
    password: lamp_redis
    database: 0
  rabbitmq:
    enabled: false
    ip: 81.70.207.162
    port: 5672
    username: admin
    password: admin
  mysql:
    ip: 81.70.207.162
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: lamp_defaults
    username: root
    password: fYTTIHITbf1EaZdCeQaPYEJTVf4363AT
    url: jdbc:mysql://${lamp.mysql.ip}:${lamp.mysql.port}/${lamp.mysql.database}?characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true
